"""Generate OpenAPI 3.0 and Postman collection documents from discovered endpoints.

Accepts either repo routes (path + method + params) or web-observed endpoints (full
URLs + status). Produces standards-compliant artifacts consumers can import into
Swagger UI, Postman, Insomnia, or codegen tools.
"""
from __future__ import annotations

from urllib.parse import urlparse


def _param_objects(params: list[str]) -> list[dict]:
    return [
        {"name": p, "in": "path", "required": True, "schema": {"type": "string"}}
        for p in params
    ]


def build_openapi(title: str, base_url: str, endpoints: list[dict]) -> dict:
    """endpoints: list of {method, path, params, auth, status, summary}."""
    paths: dict[str, dict] = {}
    uses_auth = False
    for ep in endpoints:
        path = ep["path"] or "/"
        method = ep["method"].lower()
        if method not in ("get", "post", "put", "patch", "delete", "head", "options"):
            continue
        operation: dict = {
            "summary": ep.get("summary") or f"{ep['method']} {path}",
            "responses": {
                str(ep.get("status") or 200): {"description": "Observed response"}
            },
        }
        if ep.get("params"):
            operation["parameters"] = _param_objects(ep["params"])
        if ep.get("auth"):
            operation["security"] = [{"bearerAuth": []}]
            uses_auth = True
        if method in ("post", "put", "patch"):
            operation["requestBody"] = {
                "content": {"application/json": {"schema": {"type": "object"}}}
            }
        paths.setdefault(path, {})[method] = operation

    doc: dict = {
        "openapi": "3.0.3",
        "info": {"title": title, "version": "1.0.0",
                 "description": "Auto-generated by EngineerOS API Intelligence."},
        "paths": paths,
    }
    if base_url:
        doc["servers"] = [{"url": base_url}]
    if uses_auth:
        doc["components"] = {
            "securitySchemes": {"bearerAuth": {"type": "http", "scheme": "bearer"}}
        }
    return doc


def build_postman(name: str, base_url: str, endpoints: list[dict]) -> dict:
    items = []
    for ep in endpoints:
        path = (ep["path"] or "/").lstrip("/")
        raw = f"{base_url.rstrip('/')}/{path}" if base_url else ep.get("url", ep["path"])
        parsed = urlparse(raw)
        item: dict = {
            "name": f"{ep['method']} {ep['path']}",
            "request": {
                "method": ep["method"].upper(),
                "header": ([{"key": "Authorization", "value": "Bearer {{token}}"}]
                           if ep.get("auth") else []),
                "url": {
                    "raw": raw,
                    "protocol": parsed.scheme or "https",
                    "host": (parsed.netloc or "{{base_url}}").split("."),
                    "path": [seg for seg in (parsed.path or "").split("/") if seg],
                },
            },
        }
        if ep["method"].upper() in ("POST", "PUT", "PATCH"):
            item["request"]["body"] = {"mode": "raw", "raw": "{}",
                                       "options": {"raw": {"language": "json"}}}
        items.append(item)
    return {
        "info": {
            "name": name,
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "description": "Auto-generated by EngineerOS API Intelligence.",
        },
        "item": items,
        "variable": [{"key": "base_url", "value": base_url or "https://api.example.com"}],
    }
